version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: black
    versions:
    - 20.8b1
    - 21.4b0
  - dependency-name: pylint
    versions:
    - 2.6.0
    - 2.6.2
    - 2.7.0
    - 2.7.1
    - 2.7.2
    - 2.7.4
    - 2.8.1
  - dependency-name: youtube-dl
    versions:
    - 2021.1.24.1
    - 2021.2.10
    - 2021.2.22
    - 2021.2.4.1
    - 2021.3.14
    - 2021.3.2
    - 2021.3.25
    - 2021.3.3
    - 2021.3.31
    - 2021.4.1
    - 2021.4.17
    - 2021.4.7
  - dependency-name: flake8
    versions:
    - 3.8.4
    - 3.9.0
  - dependency-name: discord-webhook
    versions:
    - 0.11.0
    - 0.12.0
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: mypy
    versions:
    - "0.800"
  - dependency-name: aiohttp
    versions:
    - 3.7.3
