jobs:
    include:
        - stage: Docker Release
          script: ./deploy.sh
          deploy:
              provider: releases
              api_key: $GITHUB_OAUTH_TOKEN
              skip_cleanup: true
              on:
                  tags: true
