dist: xenial
language: python
services:
    - docker
python:
    - "3.7"
# pytest
script: pytest
# Docker release
deploy:
    - provider: script
      script: deploy.sh
      deploy:
          on:
              tags: true
