dist: xenial
language: python
services:
    - docker
python:
    - "3.7"
# pytest
script: pytest
# Docker release
deploy:
    - provider: script
      script: deploy.sh
      on:
          branch: master
          tags: true
