version: "3.1"
services:
    message_broker:
        image: eclipse-mosquitto
        restart: always
    configurator:
        image: nimashoghi/configurator-server
        environment:
            - SCHEMA_FILE=/app/settings.schema.json
            - SETTINGS_FILE=/app/settings.json
            - UPDATE_PASSWORD=wG6gIvi7jE49yaNH5gRbNMCiUvcTn5IOCClsIPhcwkysE1i63wM41hml8GdRTTT6
        volumes:
            - ./settings.json:/app/settings.json
            - ./settings.schema.json:/app/settings.schema.json
        ports:
            - "80:80"
    youtube_service:
        build: .
        command: python -m app.services.youtube
        environment:
            - SETTINGS_FILE=/app/settings.json
        volumes:
            - ./logs/youtube-service:/app/logs
            - ./pickles:/app/pickles
            - ./settings.json:/app/settings.json
        restart: always
        stdin_open: true
        tty: true
        depends_on:
            - message_broker
            - configurator
    podbean_service:
        build: .
        command: python -m app.services.podbean
        environment:
            - SETTINGS_FILE=/app/settings.json
        volumes:
            - ./logs/podbean-service:/app/logs
            - ./pickles:/app/pickles
            - ./settings.json:/app/settings.json
        ports:
            - "23808:23808"
        restart: always
        stdin_open: true
        tty: true
        depends_on:
            - message_broker
            - configurator
            - youtube_service
    discord_service:
        build: .
        command: python -m app.services.discord
        environment:
            - SETTINGS_FILE=/app/settings.json
        volumes:
            - ./logs/discord-service:/app/logs
            - ./pickles:/app/pickles
            - ./settings.json:/app/settings.json
        restart: always
        stdin_open: true
        tty: true
        depends_on:
            - message_broker
            - configurator
            - youtube_service
    wordpress_service:
        build: .
        command: python -m app.services.wordpress
        environment:
            - SETTINGS_FILE=/app/settings.json
        volumes:
            - ./logs/wordpress-service:/app/logs
            - ./pickles:/app/pickles
            - ./settings.json:/app/settings.json
        restart: always
        stdin_open: true
        tty: true
        depends_on:
            - message_broker
            - configurator
            - youtube_service
    wordpress:
        image: wordpress
        restart: always
        ports:
            - 8080:80
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: exampleuser
            WORDPRESS_DB_PASSWORD: examplepass
            WORDPRESS_DB_NAME: exampledb
        depends_on:
            - db
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: exampledb
            MYSQL_USER: exampleuser
            MYSQL_PASSWORD: examplepass
            MYSQL_RANDOM_ROOT_PASSWORD: "1"
        volumes:
            - mysql-data-volume:/var/lib/mysql
volumes:
    mysql-data-volume:
