version: "3.1"
services:
    watcher:
        build: .
        environment:
            - SETTINGS_FILE=/app/settings.json
        volumes:
            - ./pickles:/app/pickles
        ports:
            - "23808:23808"
        restart: always
        stdin_open: true
        tty: true
